### ISSUE TITLE
Pandas.DataFrame doesn't preserve the column order when converting from a DataFrames.DataFrame

### ISSUE THREAD

**Issue by dimili** [JuliaPy/Pandas.jl#72]
When converting from a DataFrames.DataFrame, the order of the columns is not preserved. Instead, the columns are sorted in alphabetical order. Is this intentional?

```
using DataFrames
import Pandas

df = DataFrame(C = 1:4, A = 5:8, B = 9:12)
pdf = Pandas.DataFrame(df)
```

```
print(df)
4×3 DataFrame
│ Row │ C     │ A     │ B     │
│     │ Int64 │ Int64 │ Int64 │
├─────┼───────┼───────┼───────┤
│ 1   │ 1     │ 5     │ 9     │
│ 2   │ 2     │ 6     │ 10    │
│ 3   │ 3     │ 7     │ 11    │
│ 4   │ 4     │ 8     │ 12    │
```
```
print(pdf)
   A   B  C
0  5   9  1
1  6  10  2
2  7  11  3
3  8  12  4
```

**Comment by PallHaraldsson** [comment]
It's probably not intentional, and isn't even always in alphabetical order. It's because Dicts in Julia do not guarantee any order (OrderedDicts do, and possibly a better way to do that, as it's not in the standard library):

https://github.com/JuliaPy/Pandas.jl/blob/96df9260b311c5aa5a5ceea33d473f1ccf57c2c2/src/tabletraits.jl#L31

cols = Dict{Symbol,Any}(i[1]=>i[2] for i in zip(column_names, columns))

When converting (Name was first colum) I got:

```
julia> pdf
    Age  Income  Children   Name
0  34.0  120000         2   John
```

PandasLite.jl gave me the same order:
