### ISSUE TITLE
Add link to DataFrames.jl to README and docs

### ISSUE THREAD

**Issue by juliohm** [JuliaPy/Pandas.jl#87]
New Julia users repeatedly ask on forums for the equivalent of Pandas in Julia. Given that DataFrames.jl is the de-facto standard in native Julia, it would be awesome if the README of Pandas.jl could cite the package at the very top, possibly highlight the link.

Example of question: https://discourse.julialang.org/t/pandas-equivalent-library/26501

**Comment by malmaud** [comment]
I'd definitely welcome a PR to add a section to the README with related packages and how they differ, which could list DataFrames.jl at the top. 

I'm reluctant to add it to very top of the README since I think that the name and documentation of this package make it pretty clear that this is just a wrapper over the Python Pandas library, so I'm not convinced there is significant confusion between this and DataFrames.jl that would merit such a prominent positioning.
