### ISSUE TITLE
Shouldn't this (converting Pandas to DataFrames) be possible?

### ISSUE THREAD

**Issue by KwatMDPhD** [JuliaPy/Pandas.jl#88]

**Comment by KwatMDPhD** [comment]
<img width="1124" alt="Screen Shot 2022-02-05 at 00 21 35" src="https://user-images.githubusercontent.com/7741548/152632748-dca913c5-d3ae-4214-a2a3-d0690790ba6a.png">

**Comment by KwatMDPhD** [comment]
<img width="883" alt="Screen Shot 2022-02-05 at 09 43 45" src="https://user-images.githubusercontent.com/7741548/152650551-1d1dc454-1b4a-4087-a625-2a1fc22d0098.png">

**Comment by bkamins** [comment]
The issue is that it seems that Pandas.jl does not correctly implement Tables.jl table interface.

**Comment by nalimilan** [comment]
The reason is probably that `Tables.rowaccess` and `Tables.columnaccess` return `true` but that corresponding methods `Tables.rows` and `Tables.columns` are not defined, contrary to that the Tables.jl documentation requires. The two latter methods are somewhat implemented via the Tables.jl fallbacks that call TableTraits methods, but their interaction with `Tables.rowaccess` and `Tables.columnaccess` isn't super clear. Adding `Tables.rows` and `Tables.columns` definitions should be trivial.

BTW, probably only column access is needed, Tables.jl provides everything automatically to iterate over rows for consumers that need it.
